// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "PracticalCopy": {
    "header": "Somthing Good Is Coming...",
    "subheader": "Personalized weekly meals — planned by our chefs and delivered to your door.<br></br>No stress. No cooking. No planning."
  },
  "EmotionalCopy": {
    "header": "Feels like home, tastes like love.",
    "subheader": "Weekly Persian meals, planned and prepared like mom would — enjoy comfort without the cooking."
  },
  "LocaleLayout": {
    "siteName": "Mamanpaz meals",
    "title": "Get Early Access to Mamanpaz Meals",
    "description": "Subscription-based Persian meals, planned and delivered"
  },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, fa {🇮🇷 فارسی} en {🇨🇦 English} other {Unknown}}"
  },
  "WaitlistForm": {
    "button": "Join Now",
    "name": "Name",
    "postCode": "Postal code",
    "phone": "Phone number",
    "phoneValidation": "Enter a 10-digit phone number",
    "success": "Welcome to the family!<br></br>We'll message you as soon as we launch",
    "duplicate": "You're already on our list! We'll be in touch soon.",
    "shareText": "💌 Invite friends — and enjoy our referral discounts!",
    "copy": "Copy",
    "copied": "Copied to clipboard!",
    "nameMinLength": "Name must be at least 2 characters",
    "nameMaxLength": "Name must be less than 100 characters", 
    "invalidNameCharacters": "Name can only contain letters, spaces, hyphens, and apostrophes",
    "invalidPostalCode": "Invalid Canadian postal code format. Expected format: A1A 1A1",
    "invalidPhone": "Invalid Canadian phone number"
  },
  
  "SocialProof": {
    "memberCount": "{count,number}",
    "members": " people are hungry",
    "hook": "There is still room for you too",
    "launchDateLabel": "Toronto Launch date",
    "launchDate": "September 1, 2025"
  },
  "Manifest": {
    "name": "Mamanpaz Meals"
  },
  "CTA": {
    "button":"Get Your Subscription",
    "dialogTitle": "Registration form",
    "dialogDescription": ""
  }
};
export default messages;