// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "HomePage": {
    "title": "Hi from Mamanpaz",
    "about": "Go to the about page"
  },
  "PracticalCopy": {
    "header": "Dinner? <nosplit>Already handled.</nosplit>",
    "subheader": "Weekly Persian meals, chef-prepared and delivered to your door.<br></br>No planning, no cooking, no stress."
  },
  "EmotionalCopy": {
    "header": "Feels like home, tastes like love.",
    "subheader": "Weekly Persian meals, planned and prepared like mom would — enjoy comfort without the cooking."
  },
  "LocaleLayout": {
    "title": "Mamanpaz meals"
  },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, fa {🇮🇷 فارسی} en {🇨🇦 English} other {Unknown}}"
  },
  "CTAv1": {
    "button": "Join the waitlist",
    "hook": "{count, number} people signed up",
    "announcement": "Toronto - {day, number} days, {hour, number} hours until launch"
  }
};
export default messages;