// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "HomePage": {
    "title": "Hi from Mamanpaz",
    "about": "Go to the about page"
  },
  "LocaleLayout": {
    "title": "Mamanpaz meals"
  },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, fa {🇮🇷 فارسی} en {🇨🇦 English} other {Unknown}}"
  }
};
export default messages;